### ISSUE TITLE
Enhancement :: Copyright year on the footer can be automatically updated.

### ISSUE THREAD

**Issue by Hardly-Human** [ggeeks/ggeeks.github.io#17]
we can automate the Copyright year to avoid maintenance overhead of having to change it in all html files with one line of code..

`document.getElementById("year").innerText = (new Date()).getFullYear()`

Placing it in main.js file changes all the html page footers automatically..

**Comment by supsa-ak** [comment]
Hey @ssahibsingh @gurtaransingh01 please consider #18 PR. The issue opened by @Hardly-Human is solved completely. If not have to merge now it is fine. As of time constraints can you just put 'hacktoberfest-accepted' label to #18 PR early as possible.
